### ISSUE TITLE
App says I have custom Jailbreak

### ISSUE THREAD

**Issue by vmedina619** [sektioneins/syssecinfo#1]
Hello, 

Your app is awesome and thankfully I got it installed prior to its removal. I just bought a new iPhone 8 Plus and did a restore from an old backup; hence the reason I was able to keep the app. On my old phone, the app did say I had a custom jailbreak but nothing of importance was red. Now, a lot of items are red and from what I read, they mean my phone is jailbreak and I should contact you. 

Below is a screenshot of the red items. I appreciate any help you can provide me with. 
![img_2605](https://user-images.githubusercontent.com/32345814/30942216-72f57e2a-a39e-11e7-902d-051f3f1f1107.PNG)

**Comment by powtac** [comment]
Same for me!

**Comment by peter17ji** [comment]
It's a dead project, dude, so i0nic isn't coming to respond. Newer iOS disable some security measures on boot because Apple have better ones. Stay calm.

**Comment by vmedina619** [comment]
Thanks for dropping a comment. Kinda figured after going months without hearing back from them. Since they left their support page up, I gave it a go in hopes that they would. Oh well. Thanks again.

**Comment by bef** [comment]
A custom jailbreak alert is most likely perfectly normal. Unfortunately Apple does not permit us to update the app to fit current iOS versions. Please read the entire story about the app here: https://sektioneins.de/en/blog/16-08-11-sysinfo-what-happened.html

**Comment by vmedina619** [comment]
Thanks Bef for responding, I will disregard that alert then and remove the app.

**Comment by XanaduQ** [comment]
To the App Author: I cannot get to the current ios anyway. This app would be very helpful to me. If you would please repost it, I would appreciate it. I will report my findings to you to share. If you cannot, and you have other suggestions, please feel free to contact me through the board.
