### ISSUE TITLE
Found fake signed applications

### ISSUE THREAD

**Issue by rexclay** [sektioneins/syssecinfo#3]
Can you tell me how i can find out more about this issue? “Fake signed: /var/containers/Bundles/Application/EB0C477F-5A18-4A12-“

**Comment by abk163** [comment]
What can I do when this

**Comment by bef** [comment]
Unfortunately the app has been removed from the app store in 2016. Any "fake signatures" or other findings are not reliable anymore. Please see https://sektioneins.de/en/blog/16-08-11-sysinfo-what-happened.html
