### ISSUE TITLE
Security issues 

### ISSUE THREAD

**Issue by staycool72** [sektioneins/syssecinfo#5]
Hi i am experiencing security issues with my iPhone 6s, my phone has never been jailbroken, I supposedly get email from me but from a different email address and my saved fingerprints stop working. I took snapshots from the Sectioneins SysSecInfo app and found issues, however I'm unable to upload pics from my phone. Please help me

**Comment by bef** [comment]
Unfortunately our app syssecinfo was removed from the app store in 2016, so any results are most likely not reliable. Please see https://sektioneins.de/en/blog/16-08-11-sysinfo-what-happened.html
